env:
  node: true
  es2020: true

ignorePatterns:
  - dist

extends:
  - plugin:@foxglove/base
  - plugin:@foxglove/jest

overrides:
  - files: ["examples/**/*.ts"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: [./examples/tsconfig.json]
  - files: ["src/**/*.ts"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: [./tsconfig.json, ./tsconfig.dts.json]
